name = "engage-youth-web"
compatibility_date = "2025-05-14"
pages_build_output_dir = "out"

# Environment variables bound to Cloudflare Pages Functions
[env.production]
vars = { ADMIN_EMAIL = "arpeth.karon@innovinlabs.com" }

[env.preview]
vars = { ADMIN_EMAIL = "arpeth.karon@innovinlabs.com" }
