export const EVENT_CATEGORIES = [
  { value: "", label: "Choose an Event Category" },
  { value: "business-professional", label: "Business & Professional" },
  { value: "charity-causes", label: "Charity & Causes" },
  { value: "community-culture", label: "Community & Culture" },
  { value: "ecological-sustainability", label: "Ecological Sustainability" },
  { value: "family-education", label: "Family & Education" },
  { value: "fashion-beauty", label: "Fashion & Beauty" },
  { value: "fighting-homelessness", label: "Fighting Homelessness" },
  { value: "film-media-entertainment", label: "Film, Media & Entertainment" },
  { value: "food-drink", label: "Food & Drink" },
  { value: "food-drives-and-distribution", label: "Food Drives and Distribution" },
  { value: "game-or-competition", label: "Game or Competition" },
  { value: "other", label: "Other" },
  { value: "performing-visual-arts", label: "Performing & Visual Arts" },
  { value: "science-technology", label: "Science & Technology" },
  { value: "sports-fitness", label: "Sports & Fitness" },
  { value: "youth-financial-literacy", label: "Youth Financial Literacy" },
] as const;

export const EVENT_TYPES = [
  { value: "", label: "Choose an Event Type" },
  { value: "appearance-or-signing", label: "Appearance or Signing" },
  { value: "attraction", label: "Attraction" },
  { value: "camp-trip-or-retreat", label: "Camp, Trip, or Retreat" },
  { value: "class-training-or-workshop", label: "Class, Training, or Workshop" },
  { value: "concert-or-performance", label: "Concert or Performance" },
  { value: "conference", label: "Conference" },
  { value: "convention", label: "Convention" },
  { value: "dinner-or-gala", label: "Dinner or Gala" },
  { value: "environment-preservation", label: "Environment Preservation" },
  { value: "festival-or-fair", label: "Festival or Fair" },
  { value: "financial-literacy-program", label: "Financial Literacy Program" },
  { value: "food-drives-and-distribution", label: "Food Drives and Distribution" },
  { value: "game-or-competition", label: "Game or Competition" },
  { value: "homelessness-support", label: "Homelessness Support" },
  { value: "meeting-or-networking-event", label: "Meeting or Networking Event" },
  { value: "other", label: "Other" },
  { value: "party-or-social-gathering", label: "Party or Social Gathering" },
  { value: "race-or-endurance-event", label: "Race or Endurance Event" },
  { value: "rally", label: "Rally" },
  { value: "screening", label: "Screening" },
  { value: "seminar-or-talk", label: "Seminar or Talk" },
  { value: "tour", label: "Tour" },
  { value: "tournament", label: "Tournament" },
  { value: "tradeshow-consumer-show-or-expo", label: "Tradeshow, Consumer Show or Expo" },
] as const;
